"""add is_revoked to refresh_tokens

Revision ID: 0d9b5a5c9244
Revises: 99c33260a36a
Create Date: 2026-06-22 21:58:44.797161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d9b5a5c9244'
down_revision: Union[str, Sequence[str], None] = '99c33260a36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_verifications', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('otp_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_otp_verifications_user_id'), 'otp_verifications', ['user_id'], unique=False)
    op.add_column('refresh_tokens', sa.Column('is_revoked', sa.Boolean(), nullable=True))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('refresh_tokens', 'is_revoked')
    op.drop_index(op.f('ix_otp_verifications_user_id'), table_name='otp_verifications')
    op.alter_column('otp_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('otp_verifications', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
