"""add share fields to posts

Revision ID: 3c7588450219
Revises: da18cf8699ad
Create Date: 2026-07-06 12:33:19.688083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7588450219'
down_revision: Union[str, Sequence[str], None] = 'da18cf8699ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    op.add_column(
        "posts",
        sa.Column(
            "is_share",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),   # <-- important
        ),
    )

    op.add_column(
        "posts",
        sa.Column(
            "original_post_id",
            sa.Integer(),
            nullable=True,
        ),
    )

    op.create_foreign_key(
        "fk_posts_original_post",
        "posts",
        "posts",
        ["original_post_id"],
        ["id"],
    )

    # Optional: remove database default afterwards
    op.alter_column(
        "posts",
        "is_share",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'original_post_id')
    op.drop_column('posts', 'is_share')
    # ### end Alembic commands ###
