"""add cascade delete for user relations

Revision ID: 4ce8cc2b0bf0
Revises: 3819a0f08980
Create Date: 2026-07-27 15:43:29.741334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce8cc2b0bf0'
down_revision: Union[str, Sequence[str], None] = '3819a0f08980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('oauth_accounts_user_id_fkey'), 'oauth_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'oauth_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('otp_verifications_user_id_fkey'), 'otp_verifications', type_='foreignkey')
    op.create_foreign_key(None, 'otp_verifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'otp_verifications', type_='foreignkey')
    op.create_foreign_key(op.f('otp_verifications_user_id_fkey'), 'otp_verifications', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'oauth_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('oauth_accounts_user_id_fkey'), 'oauth_accounts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
