"""test

Revision ID: 5827d3a94ed3
Revises: 384eca2efde7
Create Date: 2026-07-06 13:09:00.579292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5827d3a94ed3'
down_revision: Union[str, Sequence[str], None] = '384eca2efde7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('posts_original_post_id_fkey'), 'posts', type_='foreignkey')
    op.drop_column('posts', 'is_share')
    op.drop_column('posts', 'original_post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('original_post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('is_share', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('posts_original_post_id_fkey'), 'posts', 'posts', ['original_post_id'], ['id'])
    # ### end Alembic commands ###
