"""add message status field

Revision ID: 6d07ce43902c
Revises: eb254b189d6a
Create Date: 2026-07-24 18:45:30.087068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d07ce43902c'
down_revision: Union[str, Sequence[str], None] = 'eb254b189d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Add column with temporary default
    op.add_column(
        'messages',
        sa.Column(
            'status',
            sa.String(),
            nullable=False,
            server_default="sent"
        )
    )

    # 2. Remove old column
    op.drop_column(
        'messages',
        'is_read'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'status')
    # ### end Alembic commands ###
