"""add role to users

Revision ID: b80550e3fc04
Revises: 46ff3670972c
Create Date: 2026-06-29 17:01:24.750529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80550e3fc04'
down_revision: Union[str, Sequence[str], None] = '46ff3670972c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.String(),
            nullable=False,
            server_default='user'
        )
    )

    # optional cleanup (recommended)
    op.alter_column('users', 'role', server_default=None)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
