"""update social models

Revision ID: c87bc3665cf6
Revises: 00e720e74bd2
Create Date: 2026-06-30 12:52:01.324433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c87bc3665cf6'
down_revision: Union[str, Sequence[str], None] = '00e720e74bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_user_post_share')
    )
    op.drop_table('post_shares')
    op.alter_column('comments', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint(op.f('likes_user_id_post_id_key'), 'likes', type_='unique')
    op.create_unique_constraint('uq_user_post_like', 'likes', ['user_id', 'post_id'])
    op.add_column('posts', sa.Column('status', sa.String(), nullable=False))
    op.alter_column('posts', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_column('posts', 'is_archived')
    op.add_column('profiles', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('profiles', 'bio',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'bio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('profiles', 'created_at')
    op.add_column('posts', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.alter_column('posts', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('posts', 'status')
    op.drop_constraint('uq_user_post_like', 'likes', type_='unique')
    op.create_unique_constraint(op.f('likes_user_id_post_id_key'), 'likes', ['user_id', 'post_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('comments', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('post_shares',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['original_post_id'], ['posts.id'], name=op.f('post_shares_original_post_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('post_shares_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('post_shares_pkey'))
    )
    op.drop_table('shares')
    # ### end Alembic commands ###
