"""add cascade deletes

Revision ID: f45274c86860
Revises: 4ce8cc2b0bf0
Create Date: 2026-07-27 16:47:59.739276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45274c86860'
down_revision: Union[str, Sequence[str], None] = '4ce8cc2b0bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_post_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_user_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('conversation_participants_user_id_fkey'), 'conversation_participants', type_='foreignkey')
    op.drop_constraint(op.f('conversation_participants_conversation_id_fkey'), 'conversation_participants', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversation_participants', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('likes_post_id_fkey'), 'likes', type_='foreignkey')
    op.drop_constraint(op.f('likes_user_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('posts_user_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('shares_user_id_fkey'), 'shares', type_='foreignkey')
    op.drop_constraint(op.f('shares_post_id_fkey'), 'shares', type_='foreignkey')
    op.create_foreign_key(None, 'shares', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shares', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shares', type_='foreignkey')
    op.drop_constraint(None, 'shares', type_='foreignkey')
    op.create_foreign_key(op.f('shares_post_id_fkey'), 'shares', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(op.f('shares_user_id_fkey'), 'shares', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_user_id_fkey'), 'posts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_user_id_fkey'), 'likes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('likes_post_id_fkey'), 'likes', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'conversation_participants', type_='foreignkey')
    op.drop_constraint(None, 'conversation_participants', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_participants_conversation_id_fkey'), 'conversation_participants', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(op.f('conversation_participants_user_id_fkey'), 'conversation_participants', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_user_id_fkey'), 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('comments_post_id_fkey'), 'comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
